name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  workflow_dispatch: # Allow manual triggering
    inputs:
      upstream_repo:
        description: 'The upstream repository in owner/repo format'
        required: true
        type: string
        default: nautilus-wraith/.github
      upstream_default_branch:
        description: 'The default branch of the upstream repository (default: main)'
        required: false
        type: string
        default: main

jobs:
  sync-latest-from-upstream-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes main
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1 # Or another chosen action
        with:
          target_sync_branch: main # Or your default branch
          target_repo_token: ${{ secrets.PAT_FORK }}
          upstream_sync_branch: main # Upstream branch to sync from
          upstream_repo_access_token: ${{ secrets.PAT_FORK }}
          upstream_repository: ${{ github.event.inputs.upstream_repo || 'nautilus-wraith/.github' }}

  sync-latest-from-upstream-release-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes release-stable
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1 # Or another chosen action
        with:
          target_sync_branch: release-stable # Or your default branch
          target_repo_token: ${{ secrets.PAT_FORK }}
          upstream_sync_branch: release-stable # Upstream branch to sync from
          upstream_repo_access_token: ${{ secrets.PAT_FORK }}
