name: Scheduled Sync with Upstream

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  workflow_dispatch:

jobs:
  sync:
    uses: nautilus-wraith/.github/.github/workflows/sync-all-branches.yml@main
    with:
      upstream_repo: nautilus-wraith/.github
      upstream_default_branch: main 