name: Sync Fork

permissions: {}

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  workflow_dispatch: # Allow manual triggering


jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git    
        env:
          UPSTREAM_REPO_ACCESS_TOKEN: ${{ secrets.FORK_PAT }}
          UPSTREAM_SYNC_REPO: 'nautilus-wraith/.github'
          CURRENT_REPO_AND_ORG: ${{ github.repository }}
          CURRENT_REPO: ${{ github.event.repository.name }}
        run: |
          set -e
          git clone --mirror https://$UPSTREAM_REPO_ACCESS_TOKEN@github.com/$CURRENT_REPO_AND_ORG.git
          cd $CURRENT_REPO.git
          git remote set-url origin https://$UPSTREAM_REPO_ACCESS_TOKEN@github.com/$CURRENT_REPO_AND_ORG.git
          git config user.name "secops-dso"
          git config user.email "163456430+secops-dso@users.noreply.github.com"
          git remote add upstream https://$UPSTREAM_REPO_ACCESS_TOKEN@github.com/$UPSTREAM_SYNC_REPO.git
          git fetch upstream
          git push origin --all


