name: Sync All Branches with Upstream

permissions: {}

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'The upstream repository in owner/repo format'
        required: true
        type: string
        default: nautilus-wraith/.github
      upstream_default_branch:
        description: 'The default branch of the upstream repository (default: main)'
        required: false
        type: string
        default: main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and authenticate
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_FORK }}@github.com/${{ github.repository }}.git
          git remote add upstream https://x-access-token:${{ secrets.PAT_FORK }}@github.com/${{ inputs.upstream_repo }}.git
          git fetch upstream

      - name: Get all branches from upstream
        id: get_branches
        run: |
          branches=$(git branch -r | grep "upstream/" | grep -v "HEAD" | sed 's/upstream\///')
          echo "branches<<EOF" >> $GITHUB_OUTPUT
          echo "$branches" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Sync all branches
        run: |
          branches="${{ steps.get_branches.outputs.branches }}"
          echo "$branches" | while read branch; do
            if [ -n "$branch" ]; then
              git checkout -B "$branch" "upstream/$branch"
              git push origin "$branch" --force
            fi
          done 