name: Sync All Branches with Upstream

on:
  workflow_call:
    inputs:
      upstream_repo:
        required: true
        type: string
      upstream_default_branch:
        required: false
        type: string
        default: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/${{ inputs.upstream_repo }}.git
          git fetch upstream

      - name: Get all branches from upstream
        id: get_branches
        run: |
          branches=$(git branch -r | grep "upstream/" | grep -v "HEAD" | sed 's/upstream\///')
          echo "branches<<EOF" >> $GITHUB_OUTPUT
          echo "$branches" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Sync all branches
        run: |
          for branch in ${{ steps.get_branches.outputs.branches }}
          do
            git checkout -B $branch upstream/$branch
            git push origin $branch --force
          done 